# Example Config File for Pivot Track
# Configuration for logging
logging:
  level: "INFO"
  logfile: "pivottrack.log"   # Can also be full path
# Configuration of connectors
connectors:
  # Find your Shodan API key on https://account.shodan.io
  shodan:
    api_key: "CHANGEME"
    rate_limit: 1     # API request per second
  # Find your Censys API key on https://search.censys.io/account/api
  censys:
    api_id: "CHANGEME"
    api_secret: "CHANGEME"
    rate_limit: 1     # API request per second
    enabled: False
  rabbitmq:
    host: "localhost"
    port: 5672
    virtual_host: "/"
    username: "CHANGEME"
    password: "CHANGEME"
    results_exchange: "pivottrack-results"