name: pivottrack
services:
  pivottrack-publisher:
    image: pivottrack:latest
    build: .
    container_name: pivottrack-publisher
    entrypoint: poetry run pivottrack service publish-definitions  
    environment:
      - PIVOTTRACK_CONFIG=/pivottrack/config/${PIVOTTRACK_CONFIG_FILE}
      - PIVOTTRACK_TRACK_DEFINITIONS=/pivottrack/definitions/
      - PIVOTTRACK_TRACK_INTERVAL=${PIVOTTRACK_TRACK_INTERVAL}
      - PIVOTTRACK_CONFIG_FILE=${PIVOTTRACK_CONFIG_FILE}
    volumes:
      - ${PIVOTTRACK_CONFIG_FOLDER}:/pivottrack/config/:ro
      - ${PIVOTTRACK_LOG_FOLDER}:/pivottrack/logging/
      - ${PIVOTTRACK_DEFINITION_FOLDER}:/pivottrack/definitions/:ro
    depends_on:
      tenzir-node:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      pivottrack-subscriber:
        condition: service_started
  pivottrack-subscriber:
    image: pivottrack:latest
    build: .
    container_name: pivottrack-subscriber
    entrypoint: poetry run pivottrack service subscribe-definitions  
    environment:
      - PIVOTTRACK_CONFIG=/pivottrack/config/${PIVOTTRACK_CONFIG_FILE}
      - PIVOTTRACK_TRACK_DEFINITIONS=/pivottrack/definitions/
      - PIVOTTRACK_TRACK_INTERVAL=${PIVOTTRACK_TRACK_INTERVAL}
      - PIVOTTRACK_CONFIG_FILE=${PIVOTTRACK_CONFIG_FILE}
    volumes:
      - ${PIVOTTRACK_CONFIG_FOLDER}:/pivottrack/config/:ro
      - ${PIVOTTRACK_LOG_FOLDER}:/pivottrack/logging/
      - ${PIVOTTRACK_DEFINITION_FOLDER}:/pivottrack/definitions/:ro
    depends_on:
      tenzir-node:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MGM_PORT}:15672
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 15s
        retries: 1
  tenzir-node:
    container_name: "tenzir"
    image: "tenzir/tenzir:latest"
    pull_policy: always
    environment:
      - TENZIR_TOKEN=${TENZIR_TOKEN}
      - TENZIR_PLATFORM_CONTROL_ENDPOINT=${TENZIR_PLATFORM_CONTROL_ENDPOINT}
      - TENZIR_ENDPOINT=${TENZIR_ENDPOINT}
      - PT_RABBITMQ_USER=${PT_RABBITMQ_USER}
      - PT_RABBITMQ_PASS=${PT_RABBITMQ_PASS}
      - PT_RABBITMQ_HOST=${PT_RABBITMQ_HOST}
      - PT_RABBITMQ_PORT=${PT_RABBITMQ_PORT}
    entrypoint:
      - tenzir-node
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: tenzir --connection-timeout=15s --connection-retry-delay=1s 'api "/ping"'
      interval: 15s
      retries: 1
    volumes:
      - ./tenzir.yaml:/opt/tenzir/etc/tenzir/tenzir.yaml