[tool.poetry]
name = "pivot-track"
version = "0.1.0"
description = ""
authors = ["Christoph Lobmeyer <lochr@posteo.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
